# Generated by Django 4.2.3 on 2023-08-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="address",
            new_name="addresse",
        ),
    ]
